[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.3.0"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  name = "github.com/prometheus/common"
  branch = "master"

[[constraint]]
  branch = "release-2.10_fork_promxy"
  name = "github.com/prometheus/prometheus"
  source = "github.com/jacksontj/prometheus"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  branch = "master"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

# Force some transitive stuffs
[[override]]
  name = "github.com/hashicorp/consul"
  version = "v1.1.0"

[[override]]
  name = "github.com/hashicorp/serf"
  version = "v0.8.1"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "github.com/fsnotify/fsnotify"

[[override]]
  name = "github.com/cockroachdb/cockroach"
  revision = "84bc9597164f671c0130543778228928d6865c5c"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "2b1284ed4c93a43499e781493253e2ac5959c4fd"

[[override]]
  name = "k8s.io/client-go"
  version = "v11.0.0"
