
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.3.0"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "tjackson_fork_22"
  name = "github.com/prometheus/common"
  source = "github.com/jacksontj/common"

[[constraint]]
  branch = "release-2.2_fork_promxy"
  name = "github.com/prometheus/prometheus"
  source = "github.com/jacksontj/prometheus"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  branch = "master"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

# Force some transitive stuffs
[[override]]
  name = "github.com/hashicorp/consul"
  version = "v0.9.3"

[[override]]
  name = "github.com/hashicorp/serf"
  version = "v0.8.1"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "github.com/fsnotify/fsnotify"
